kind: Service
apiVersion: v1
metadata:
  name: csi-dropbox-attacher
  labels:
    app: csi-dropbox-attacher
spec:
  selector:
    app: csi-dropbox-attacher
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-dropbox-attacher
spec:
  serviceName: "csi-dropbox-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-dropbox-attacher
  template:
    metadata:
      labels:
        app: csi-dropbox-attacher
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - csi-dropboxplugin
              topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v2.0.0
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-dropbox
            type: DirectoryOrCreate
          name: socket-dir