name: Dropbox-CSI
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker image build
        run: make image-build
      - name: install minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mkdir -p /usr/local/bin/
          sudo install minikube /usr/local/bin/
          sudo snap install kubectl --classic
      - name: test cluster up
        run: make test-cluster-up && kubectl get pods -A
      - name: create secret
        run: kubectl create secret generic dropbox-csi --from-literal=token=${{ secrets.DropboxToken }}
      - name: yaml deploy
        run: make yaml-deploy
      - name: e2e tests
        run: make test
  deploy:
    runs-on: ubuntu-18.04
    needs: e2e
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker image build
        run: make image-build
      - uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: woohhan
          password: ${{ secrets.QuayPassword }}
      - name: push with latests
        run: |
          docker tag quay.io/woohhan/dropbox-csi:canary quay.io/woohhan/dropbox-csi:latest
          docker push quay.io/woohhan/dropbox-csi:latest
